require: rubocop-rspec
inherit_gem:
  rubocop-govuk:
    - "config/default.yml"
    - "config/rails.yml"

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Enabled: false

# This recently introduced cop seems to have stirred up some controversy
RSpec/ContextWording:
  Enabled: false

# This isn't supported by Mongoid
Rails/FindBy:
  Enabled: false

# This isn't supported by Mongoid
Rails/FindEach:
  Enabled: false
