require: rubocop-rspec
inherit_gem:
  rubocop-govuk:
    - "config/default.yml"
    - "config/rails.yml"

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Max: 10

# This recently introduced cop seems to have stirred up some controversy
Style/AccessModifierDeclarations:
  Enabled: false

Layout/AccessModifierIndentation:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

# Mongoid doesn't support some of the methods that Rubocop prefers
Rails/FindBy:
  Enabled: false

Rails/FindEach:
  Enabled: false
