inherit_gem:
  rubocop-govuk:
    - "config/default.yml"
    - "config/rails.yml"
    - "config/rspec.yml"

inherit_mode:
  merge:
    - Exclude

# TODO: explain or remove this override
RSpec/AnyInstance:
  Enabled: false

# This isn't supported by Mongoid
Rails/FindBy:
  Enabled: false

# This isn't supported by Mongoid
Rails/FindEach:
  Enabled: false
