development:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] || "mongodb://localhost/govuk_assets_development" %>
test:
  clients:
    default:
      uri: <%= ENV["TEST_MONGODB_URI"] || "mongodb://localhost/govuk_assets_test" %>
      options:
        read:
          mode: :primary
production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        read:
          mode: :primary
        user: <%= ENV["MONGODB_USERNAME"] || "" %>
        password: <%= ENV["MONGODB_PASSWORD"] || "" %>
